// generated by diplomat-tool
import { PairSeq } from "./PairSeq.mjs"
import { TokenSpan } from "./TokenSpan.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const EncodeResult_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.EncodeResult_destroy(ptr);
});

export class EncodeResult {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];
    
    constructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("EncodeResult is an Opaque type. You cannot call its constructor.");
            return;
        }
        
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;
        
        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            EncodeResult_box_destroy_registry.register(this, this.#ptr);
        }
    }

    get ffiValue() {
        return this.#ptr;
    }

    get(i) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 9, 4, true);
        
        const result = wasm.EncodeResult_get(diplomatReceive.buffer, this.ffiValue, i);
    
        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return new TokenSpan(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }
        
        finally {
            diplomatReceive.free();
        }
    }

    getByIdx(i) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 8, 4, false);
        
        const result = wasm.EncodeResult_get_by_idx(diplomatReceive.buffer, this.ffiValue, i);
    
        try {
            return new TokenSpan(diplomatRuntime.internalConstructor, diplomatReceive.buffer);
        }
        
        finally {
            diplomatReceive.free();
        }
    }

    len() {
        const result = wasm.EncodeResult_len(this.ffiValue);
    
        try {
            return result;
        }
        
        finally {}
    }

    isEmpty() {
        const result = wasm.EncodeResult_is_empty(this.ffiValue);
    
        try {
            return result;
        }
        
        finally {}
    }

    pairSeq() {
        const result = wasm.EncodeResult_pair_seq(this.ffiValue);
    
        try {
            return new PairSeq(diplomatRuntime.internalConstructor, result, []);
        }
        
        finally {}
    }
}