// generated by diplomat-tool
import type { PairSeq } from "./PairSeq"
import type { TokenSpan } from "./TokenSpan"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export class EncodeResult {
    

    get ffiValue(): pointer;

    get(i: number): TokenSpan | null;

    getByIdx(i: number): TokenSpan;

    len(): number;

    isEmpty(): boolean;

    pairSeq(): PairSeq;
}