// generated by diplomat-tool
import type { Strings } from "./Strings"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export class Stem {
    

    get ffiValue(): pointer;

    static create(): Stem;

    stem(strs: Array<string>): Strings;
}