// generated by diplomat-tool
import type { EncodeResult } from "./EncodeResult"
import type { TokRes } from "./TokRes"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export class Tok {
    

    get ffiValue(): pointer;

    static create(): Tok;

    tokenize(text: string): TokRes;

    tokenizeAsOffsets(text: string): EncodeResult;
}