// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export class TokenSpan {

    get start() : number;
    set start(value: number); 

    get end() : number;
    set end(value: number); 
    constructor(start: number, end: number);
}