// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

export class TokRes {
    

    get ffiValue(): pointer;

    get(i: number): string | null;

    getByIdx(i: number): string;

    len(): number;

    isEmpty(): boolean;
}